// Generated by CoffeeScript 1.3.1
(function() {

  (function(root, factory) {
    if (typeof exports === "object") {
      return module.exports = factory('spine');
    } else if (typeof define === "function" && define.amd) {
      return define(['spine'], factory);
    } else {
      if (root.Spine == null) {
        root.Spine = {};
      }
      return root.Spine.Local = factory(root.Spine);
    }
  })(this, function(Spine) {
    Spine.Model.Local = {
      extended: function() {
        this.change(this.saveLocal);
        return this.fetch(this.loadLocal);
      },
      saveLocal: function() {
        var result;
        result = JSON.stringify(this);
        return localStorage[this.className] = result;
      },
      loadLocal: function() {
        var result;
        result = localStorage[this.className];
        return this.refresh(result || [], {
          clear: true
        });
      }
    };
    return Spine.Model.Local;
  });

}).call(this);
